import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import InvoiceForm from '../components/InvoiceForm'
import InvoiceListContainer from '../components/InvoiceListContainer'
import InvoiceListHeader from '../components/InvoiceListHeader'
import { useGlobalContext } from '../context/globalContext'

export default function Home() {
  const { showForm, setShowForm, pageStyles } = useGlobalContext()
  return (
    <div className={`${pageStyles} min-h-screen  font-Jost overflow-x-hidden`}>
      <Head>
        <title>Invoice App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='p-4 relative sm:p-12 lg:px-48 mt-16 lg:flex lg:flex-col items-center lg:mt-0'>
        <InvoiceListHeader setShowForm={setShowForm} />
        <InvoiceListContainer showForm={showForm} setShowForm={setShowForm} />
      </main>
    </div>
  )
}
